### ISSUE TITLE
GeForce 2000 D.diffuseMode(DIFFUSE_BURLEY) shader problem

### ISSUE THREAD

**Issue by Brouilles** [Esenthel/EsenthelEngine#21]
Hi, 
I have buy the Esenthel RTS (Source Code). But I have like noise in the render of 3D elements. I havent done any modification on the code. And I using the last version of the engine downloable on the website.

See screenshot:

![image](https://user-images.githubusercontent.com/1573282/92574027-db7a8280-f286-11ea-9b5e-40f673b57148.png)

Specs:
Windows 10 2004 / 19041.508
NVIDIA RTX 2060

I don't have problem on the menu or GUI / 2D elements.
Thanks!

**Comment by Brouilles** [comment]
And I have the same problem in the editor.

![image](https://user-images.githubusercontent.com/1573282/92574978-14ffbd80-f288-11ea-9a6a-5dc84c2f1fed.png)

**Comment by GregSlazinski** [comment]
Hello,

This is a bug in Nvidia Geforce driver/cards

https://esenthel.com/forum/showthread.php?tid=10068
https://esenthel.com/forum/showthread.php?tid=9978
https://esenthel.com/forum/showthread.php?tid=9791&pid=57254#pid57254

One workaround is to change Editor Video Options \ Advanced \ Diffuse Mode to Lambert (instead of Burley/Disney)
in code its: D.diffuseMode(..);

Another workaround is to disable half precision shaders:
replace this line in engine source:
"AMD=ContainsAll(D.deviceName(), "Radeon", true, true);"
with
"AMD=true;"

I don't have a 2000 GeForce series so I can't do anything. Mine is 1050 Ti and works fine.

2000 have problems handling this code:
https://github.com/Esenthel/EsenthelEngine/blob/master/Engine/Source/Shaders/!Header.h#L1783
Which works fine on Intel UHD 630 (with 16-bit halfs) and Mobile GPU's (with 16-bit halfs)
I don't see any problem with that code, so it looks like the driver is at fault.

Can you report this problem to Nvidia?
https://forums.developer.nvidia.com/c/visual-and-game-development/directx-and-direct-compute/196

**Comment by Brouilles** [comment]
Thanks!
When I have time, I would think of posting it on the nvidia forum.
I'll also check the shader code to see. And do some testing as I have a graphics card with the problem. I just made a graphics card change. Why I was surprised!

Have a good day!

**Comment by GregSlazinski** [comment]
Thanks, here's the doc on how to recompile shaders:
https://github.com/Esenthel/EsenthelEngine/blob/master/Extra/Recompiling%20Shaders.md

The affected shader is "MAIN"

**Comment by GregSlazinski** [comment]
Can anyone affected by this problem tell me if  the problem occurs in the 
"Apps\12 - Rendering\01 - Rendering" tutorial, from the default Editor Tutorials?
I want to submit the report to Nvidia, but I must know if the problem can be seen there.

**Comment by GregSlazinski** [comment]
Bug reported to Nvidia here - https://forums.developer.nvidia.com/t/graphics-driver-bug-related-to-half-precision-shaders-on-2000-series/167283

**Comment by GregSlazinski** [comment]
Out of curiosity, is this problem still present on latest drivers?

**Comment by Brouilles** [comment]
Driver Update today. I check when I can.

**Comment by Brouilles** [comment]
From my side it seems to be working fine. With GeForce RTX 2060, driver version 461.92.
PS: Esenthel RTS (Source Code) generates a compilation error with the latest stable Esenthel version available on the site.

**Comment by GregSlazinski** [comment]
I've just applied a workaround provided by Nvidia to the source code.
