### ISSUE TITLE
Wrong language tag

### ISSUE THREAD

**Issue by Coriiander** [Esenthel/EsenthelEngine#36]
This repository is marked with the c language, while it cannot possibly compile in c. There's alot of C++, which is not c. Could you please correct this? I'm sick and tired of  C++ code unjustly polluting c tagged queries. C++ has its own tag.

**Comment by GregSlazinski** [comment]
Please show where is the problem exactly

**Comment by FinnT730** [comment]
I feel like this is something Github is doing automaticly.
Yes, maybe Projects can change the languages in the "Languages" list (shown in the image below)
But I think most of this is automaticly generated by github, based on the files.
C and C++ are very similar, and it might be getting confused because of that.


 ![image](https://user-images.githubusercontent.com/7442674/161506046-5b3fc183-02a3-4f38-a3f2-7ba93b63e57c.png)
